eatery/eatery/urls.py
from django.urls import include, path 
from django.contrib import admin

urlpatterns = [ 
     path('', include('order.urls')), 
     path('admin/', admin.site.urls),
]

eatery/order/urls.py
from django.urls import path

from . import views
app_name = 'order'
urlpatterns = [
     path('', views.home_page, name='home_page'),
]

eatery/order/models.py
from django.db import models

class Order(models.Model):
     order = models.CharField(max_length=180, null=True, blank=True)
     address = models.CharField(max_length=180, null=True, blank=True)

eatery/order/views.py
from django.shortcuts import render
from . models import Order
def home_page(request):

    if request.method == 'POST':
        food_name = request.POST.get('food_name')
        address = request.POST.get("address")
        order_obj = Order.objects.create(
            order = food_name,
            address = address,
        )
        return render(request, 'order/home_page.html', {'foods': order_obj})

    return render(request, 'order/home_page.html') 

eatery/order/templates/order/home_page.html
<!DOCTYPE html>
<html>
<head>
	<title>Prince Benson Waimai</title>
</head>
<body>
	<h1>Prince Benson Fusion Restaurant</h1>

	<h2>Tasty Treats To Your Door</h2>

	<!-- Item 1 -->
	<p>Cake: 12RMB</p>
	<img src="https://tse4-mm.cn.bing.net/th?id=OIP.PPe6I6KT1u7PRRmQS9MZKAHaHa&w=182&h=182&c=7&o=5&pid=1.7">
	<br>

	<!-- Item 2 -->
	<p>Hamburger: 20RMB</p>
	<img src="https://tse4-mm.cn.bing.net/th?id=OIP.0_f3FDbw9OTHxyx5521I_QHaFj&w=243&h=182&c=7&o=5&pid=1.7">

	<!-- Item 3 -->
	<p>Chips: 10RMB</p>
	<img src="https://tse3-mm.cn.bing.net/th?id=OIP.cAanI1gSvXoAbw8-zskbvgHaE8&w=262&h=175&c=7&o=5&pid=1.7">

    <!-- Order Form -->
    <h2>Place your Order</h2>
    <form action="{% url 'order:home_page' %}" method="POST">
        {% csrf_token %}    
        <input type="text" name="food_name" placeholder="Please Type Which food You Want"><br>
        <textarea name="address" placeholder="Please Type Your Address"></textarea><br>
        <input type="submit" value="Place Your Order">
    </form> 

    <!-- Show Order -->
    <h1>Your Order:</h1>
    <p>Food Ordered: {{foods.order}}</p>
    <p>Delivery Address: {{foods.address}}</p>

</body>
</html>